version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugin:/plugins
    environment:
        - NEO4J_AUTH=neo4j/ForgetMeN0t
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "7687:7687"
  
  db_init:
    image: db_init
    build:
      context: ./db_init_container 
      dockerfile: Dockerfile.yaml
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
        - NEO4J_AUTH=neo4j/ForgetMeN0t

  bacon_server:
    image: bacon_server
    build:
      context: ./server_container
      dockerfile: Dockerfile.yaml
    depends_on:
      db_init:
        condition: service_completed_successfully
    environment:
        - NEO4J_AUTH=neo4j/ForgetMeN0t
    restart: always
    ports:
      - "5000:5000"

  bacon_frontend:
    image: bacon_frontend
    build:
      context: ./frontend_container
      dockerfile: Dockerfile.yaml
    depends_on:
      bacon_server:
        condition: service_started
    restart: always
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /$HOME/rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      retries: 3
      timeout: 5s

  db_writer:
    image: db_writer
    build:
      context: ./db_writer_container
      dockerfile: Dockerfile.yaml
    depends_on:
      db_init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    environment:
        - NEO4J_AUTH=neo4j/ForgetMeN0t
