apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: service-neo4j
  name: service-neo4j
spec:
  ports:
    - name: "7687"
      port: 7687
      targetPort: 7687
  selector:
    io.kompose.service: service-neo4j
